"""Add oauth_temporary_tokens table

Revision ID: 380e4bff066b
Revises: c2c2407b044c
Create Date: 2025-10-28 22:18:53.752243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380e4bff066b'
down_revision: Union[str, Sequence[str], None] = 'c2c2407b044c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_temporary_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_temporary_tokens_id'), 'oauth_temporary_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_temporary_tokens_token'), 'oauth_temporary_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_temporary_tokens_token'), table_name='oauth_temporary_tokens')
    op.drop_index(op.f('ix_oauth_temporary_tokens_id'), table_name='oauth_temporary_tokens')
    op.drop_table('oauth_temporary_tokens')
    # ### end Alembic commands ###
